// Función para generar campos de entrada para los parciales basado en el número ingresado por el usuario
function generateFields() {
    // Obtenemos el número de parciales que el usuario ha ingresado en el formulario...
    const numParciales = document.getElementById('numParciales').value;
    
    // Obtenemos el contenedor donde se agregarán los campos de parciales...
    const parcialesContainer = document.getElementById('parcialesContainer');
    
    // Limpiamos el contenido del contenedor para eliminar campos anteriores si los hubiera (por si las moscas...)
    parcialesContainer.innerHTML = '';

    // Creamos un campo de entrada para cada parcial basado en el número ingresado...
    for (let i = 0; i < numParciales; i++) {
        // Creamos un nuevo div para contener la etiqueta y el campo de entrada del parcial...
        const parcialItem = document.createElement('div');
        parcialItem.className = 'parcial-item';  // Agregamos una clase CSS para aplicar estilos al contenedor de etiqueta y campo...

        // Creamos una nueva etiqueta para el campo del parcial...
        const label = document.createElement('label');
        label.textContent = `Parcial ${i + 1}:`;  // Establecemos el texto de la etiqueta para el parcial actual...

        // Creamos un nuevo campo de entrada para el valor del parcial...
        const input = document.createElement('input');
        input.type = 'number';  // Establecemos el tipo de entrada como número...
        input.name = `parcial${i + 1}`;  // Asignamos un nombre único a cada campo de entrada...
        input.min = '0';  // Establecemos el valor mínimo que el usuario puede ingresar...
        input.max = '10';  // Establecemos el valor máximo que el usuario puede ingresar...
        input.step = '0.01';  // Definimos el incremento de valores aceptados por el campo (hasta dos decimales)...
        input.required = true;  // Establecemos que este campo es obligatorio para enviar el formulario...

        // Agregamos la etiqueta y el campo de entrada al contenedor del parcial...
        parcialItem.appendChild(label);
        parcialItem.appendChild(input);
        
        // Agregamos el nuevo contenedor de parcial al contenedor principal en la página...
        parcialesContainer.appendChild(parcialItem);
        }

    // Mostramos el botón de enviar el formulario (Calcular Promedio) cuando se generan los campos de parciales...
    document.getElementById('submitBtn').style.display = 'block';
    }

// Función para validar que todos los campos de parciales tienen un valor antes de enviar el formulario
function validateForm() {
    // Obtenemos el número de parciales ingresado por el usuario...
    const numParciales = document.getElementById('numParciales').value;
    
    // Obtenemos el contenedor de parciales donde se encuentran los campos de entrada...
    const parcialesContainer = document.getElementById('parcialesContainer');

    // Recorremos todos los campos de entrada para verificar que ninguno esté vacío...
    for (let i = 0; i < numParciales; i++) {
        // Obtenemos el campo de entrada para el parcial actual...
        const input = parcialesContainer.querySelector(`input[name="parcial${i + 1}"]`);
        
        // Si el campo de entrada está vacío, mostramos una alerta y evitamos que el formulario se envíe sin estar completo...
        if (input.value === "") {
            alert("Todos los campos de parciales deben estar llenos");
            return false;  // Devolvemos falso para evitar el envío del formulario incompleto...
            }
        }
    // Si todos los campos están llenos, permitimos el envío del formulario para proceder a calcularlo en nuestro index (php)...
    return true;
    }

// Esta función se ejecuta automáticamente cuando se carga la página
window.onload = function() {
    // Limpiamos el resultado mostrado en la página si se recarga (si el tipo de navegación es 'reload')...
    if (performance.navigation.type === 1) {
        document.getElementById('result').innerHTML = '';
        }
    }